name: 'OpenConnect Action'
description: 'Sets up OpenConnect VPN and connects to a VPN server.'
inputs:
  fortissl:
    description: 'Set to true for FortiSSL VPN connection'
    required: true
    default: 'false'
  user:
    description: 'VPN Username (required for FortiSSL)'
    required: false
  password:
    description: 'VPN Password (required for FortiSSL)'
    required: false
  host:
    description: 'VPN Host (e.g., vpn.example.com)'
    required: false
  port:
    description: 'VPN Port (default is 443)'
    required: false
    default: '443'
  servercert:
    description: 'Server certificate to validate the server (optional)'
    required: false
    default: ''
  custom_command:
    description: 'Custom authentication command (only used for FortiSSL)'
    required: false
  timeout_minutes:
    description: 'Login timeout'
    required: true
    default: 5

runs:
  using: 'composite'
  steps:

    - name: Install OpenConnect
      id: install_openconnect
      shell: bash
      run: |
        sudo apt-get update && \
        sudo apt-get install -y openconnect

    - name: Give execution permissions to entrypoint.sh
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.sh

    - name: Run entrypoint.sh
      timeout-minutes: ${{ inputs.timeout_minutes }}
      uses: gacts/run-and-post-run@v1
      with:
        run: ${{ github.action_path }}/entrypoint.sh "${{ inputs.fortissl }}" "${{ inputs.user }}" "${{ inputs.password }}" "${{ inputs.host }}" "${{ inputs.port }}" "${{ inputs.servercert }}" "${{ inputs.custom_command }}"
        post: |
          sudo pkill openconnect